### ISSUE TITLE
Keeps detecting a plain text file

### ISSUE THREAD

**Issue by Caiden-P** [DarkTrick/SourceCodeVisualizer#10]
![image](https://user-images.githubusercontent.com/119334408/224833948-87fe8fc8-0a39-4303-baf6-b3f176f1400b.png)

**Comment by DarkTrick** [comment]
I'm sorry you're experiences problems with the addon :(

**Workaround:**
I had the same issues a couple of weeks ago. I could fix it by restarting VSCode

**Problem Explanation**
Unfortunately this is essentially a VSCode problem. 

_Details:_
The add-on relies heavily on VScode (and its `Language Server`) in this department. I was also trying to let the user choose the programming language in this case, but it turned out, that in cases like yours, VSCode will also not be able to provide any parsing details.

Given the problem background, I will close this issue. If you feel that's unjustified, feel free to reopen it.
